version: "3.5"
   
services:
  res_dev:
    build: .
    restart: always
    container_name: resVideo-dev
    volumes:
      - ".:/projects/projectname/"
    ports:
      - "${PORT}:8000"
    environment:
      DEBUG: "True"
    networks:
      - https
  
networks:
  https:
    external:
      name: ${HTTPS_NETWORK}
