version: '3'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8081:8000"
    networks:
      - https
networks:
  https:
    external:
      name: https_network
  
